# Generated by Django 4.0.4 on 2022-04-19 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_system_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='designation',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Star_Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('stellar_class', models.CharField(choices=[('s', 'solitary star'), ('b', 'binary system'), ('t', 'trinary system'), ('cl', 'star cluster'), ('sn', 'stellar nebula')], max_length=20)),
                ('mass', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.system')),
            ],
            options={
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Planetoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('body_type', models.CharField(choices=[('g', 'gas giant'), ('r', 'rocky planet'), ('d', 'dwarf planet')], max_length=20)),
                ('mass', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.system')),
            ],
            options={
                'ordering': ['designation'],
            },
        ),
    ]
