# Generated by Django 4.0.4 on 2022-04-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_system_designation_star_object_planetoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star_object',
            name='stellar_class',
            field=models.CharField(choices=[('sg', 'supergiant'), ('g', 'giant'), ('o', 'O-spectrum'), ('b', 'B-spectrum'), ('a', 'A-spectrum'), ('f', 'F-spectrum'), ('g', 'G-spectrum'), ('k', 'K-spectrum'), ('m', 'M-spectrum'), ('w', 'White Dwarf')], max_length=20),
        ),
    ]
