# Generated by Django 4.0.4 on 2022-04-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_system_discoverer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.CharField(choices=[('Solitary star', 'Solitary star'), ('Binary system', 'Binary system'), ('Trinary system', 'Trinary system'), ('Star cluster', 'Star cluster'), ('Stellar nebula', 'Stellar nebula')], max_length=20),
        ),
    ]
