# Generated by Django 4.0.4 on 2022-04-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_system_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='visitors',
            field=models.ManyToManyField(related_name='discoverer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='system',
            name='discoverer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
