# Generated by Django 4.0.4 on 2022-04-25 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_alter_system_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star_object',
            name='stellar_class',
            field=models.CharField(choices=[('sg', 'supergiant'), ('g', 'giant'), ('o', 'O-spectrum'), ('b', 'B-spectrum'), ('a', 'A-spectrum'), ('f', 'F-spectrum'), ('g', 'G-spectrum'), ('k', 'K-spectrum'), ('m', 'M-spectrum'), ('w', 'White Dwarf')], max_length=50),
        ),
        migrations.AlterField(
            model_name='system',
            name='discoverer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='system',
            name='visitors',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
