# Generated by Django 4.0.4 on 2022-04-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_star_object_stellar_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_object',
            name='emission_color',
            field=models.IntegerField(default=16777215),
            preserve_default=False,
        ),
    ]
